### ISSUE TITLE
missing van 

### ISSUE THREAD

**Issue by cummins24v2** [DrBooly-491/booly_marketvan#1]
is there a certain game build for this to work 
i got the tracker and went to the spot and the van was missing

**Comment by DrBooly-491** [comment]
i'm personally using 2802, but it should be loading the van after the character is selected and spawned it, you could try turning debug on and see if it prints "van spawn at" then the van coords

**Comment by cummins24v2** [comment]
i will try that now

**Comment by cummins24v2** [comment]
it didnt say spawn or anything

**Comment by DrBooly-491** [comment]
can you spawn the speedo4 normally?

**Comment by cummins24v2** [comment]
that the first thing i tried when it didnt work and it spawned fine

**Comment by DrBooly-491** [comment]
go into the 'client/component.lua' and uncomment out the forcevan command and try that?

**Comment by cummins24v2** [comment]
that didnt seem to work for some reason

**Comment by DrBooly-491** [comment]
can you try this dev version just has some added debug prints, i would like to see where its getting snagged on https://github.com/DrBooly-491/booly_marketvan/blob/dev/client/cl_main.lua

**Comment by DrBooly-491** [comment]
keep debug on for this ^^ too

**Comment by cummins24v2** [comment]
![image](https://github.com/user-attachments/assets/293f08fd-2d58-4b8f-adfa-18cbf5a5b4c4)
that the only thing im getting in f8 and server console

**Comment by DrBooly-491** [comment]
is there anything else, could you scroll up and double check?

**Comment by cummins24v2** [comment]
![image](https://github.com/user-attachments/assets/327cbef7-1ee6-4f81-b9cd-039e001d2411)

**Comment by cummins24v2** [comment]
just the proxy stuff

**Comment by DrBooly-491** [comment]
added a changed the prints and added a couple more let me know, coz this is weird https://github.com/DrBooly-491/booly_marketvan/blob/dev/client/cl_main.lua

**Comment by cummins24v2** [comment]
![image](https://github.com/user-attachments/assets/743caf63-2d0a-4c73-980d-5482263d5d9b)
this popped up but there is still no van

**Comment by DrBooly-491** [comment]
did it print this "Prop Model will load" ?

**Comment by cummins24v2** [comment]
it did not idk why im having issues

**Comment by DrBooly-491** [comment]
okay so this tells me alot now, so for some reason your game isnt registering the prop in the van "xm3_prop_xm3_crate_ammo_01a" just change the prop at line 8 to "prop_box_ammo03a_set" for me and then try

**Comment by DrBooly-491** [comment]
if that does work, i would recommend opening rockstar games launcher and verify your game files

**Comment by cummins24v2** [comment]
alright ill try that im on game build 2699 but ill verify my game files

**Comment by DrBooly-491** [comment]
![image](https://github.com/user-attachments/assets/a72cb933-c9bb-462e-8579-ae3e78e5c04b)
 i mean your verify your gta5 game files

**Comment by cummins24v2** [comment]
![image](https://github.com/user-attachments/assets/07c688fd-0248-4a30-a893-bc1263d369e0)
thanks so much for your patience

**Comment by DrBooly-491** [comment]
yep that explains that.

when did you update your gta5 files last?

**Comment by cummins24v2** [comment]
apparently i had 2 gta files on my E drive and D drive and i had gta up to date but my fivem was running on the E drive and not the D drive same thing with open iv

**Comment by DrBooly-491** [comment]
lol, check the original prop on the updated gta files, or leave it with the temp one.

happy that we got to the bottom of that
